jQuery(document).ready(function($){
    $("a[rel^='prettyPhoto']").prettyPhoto();
	$('.menu-toggle').click(function(){
		$('#nav-section').toggleClass('show-menu');
	});
	$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:true,
    /* Addition*/
    navText:['Next','Previous'],
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:3,
            nav:false
        },
        1000:{
            items:5,
            nav:true,
            loop:false
        }
    }
})
});